== Lisk Commander Documentation

Lisk Commander is a Command-Line-Interface Tool designed to facilitate
delegates, node operators, contributors to the Lisk codebase, developers
using Lisk’s infrastructure (and anyone else who’s interested) to make
use of Lisk’s functionality from the command line with ease.

Lisk Commander allows to communicate with a remote or local node and
carry out Lisk-related functionality.

This can be for example:

* create a transaction
* decrypt/encrypt passphrases or messages
* install and manage a Lisk node
* create accounts
* get delegates
* … many more examples can be found on the
link:user-guide/commands.md[commands] page.

=== Table of contents

* link:#lisk-commander-documentation[Introduction]
** link:#versions[Lisk Commander Version Reference]
** link:#setup[Setup]
*** link:#pre-installation[Pre-Installation]
*** link:#installation[Installation]
** link:#upgrade[Upgrade]
** link:#contribute-to-the-codebase[Contribute to Codebase]
* link:user-guide.md[User Guide]
* link:user-guide/lisk-core.md[Lisk Core Commands]
* link:user-guide/commands.md[General Command Reference]
* link:user-guide/sensitive-inputs.md[Sensitive Inputs]

=== Versions

Documentation on https://lisk.io/documentation[lisk.io] keeps up to date
with version updates. The table below provides an overview about the
former releases and documentation versions of Lisk Commander.

[cols=",,",options="header",]
|===
|Version |Release date (yy/mm/dd) |Documentation reference
|https://github.com/LiskHQ/lisk/releases/tag/v2.1.0[v2.2.0] |19/0x/xx
|_Current version, live on lisk.io/documentation_

|https://github.com/LiskHQ/lisk-commander/releases/tag/v2.1.0[v2.1.0]
|19/01/14
|https://github.com/LiskHQ/lisk-docs/blob/commander-2.1.0/introduction.md[Lisk
Commander 2.1 docs]

|https://github.com/LiskHQ/lisk-commander/releases/tag/v2.0.0[v2.0.0]
|18/11/14
|https://github.com/LiskHQ/lisk-docs/blob/commander-2.0.0-1.0.1/introduction.md[Lisk
Commander 2.0 docs]

|https://github.com/LiskHQ/lisk-commander/releases/tag/v1.0.0[v1.0.0]
|18/08/13
|https://github.com/LiskHQ/lisk-docs/blob/commander-1.0.0/introduction.md[Lisk
Commander 1.0 docs]
|===

=== Setup

____
Supported Platforms: Platforms with NodeJS versions 8.3 and above.
____

==== Pre-Installation

Lisk Commander requires https://nodejs.org/[Node.js] as the underlying
engine for code execution.

===== Install Node

Node.js is supported on most operating systems. Follow the instructions
for your operating system on the https://nodejs.org/en/download/[Node.js
downloads page]. Lisk-Commander requires Node.js versions 8.3 or above.
NPM is automatically installed along with Node.js.

====== Verify Node installation

Confirm that Node.js and NPM have been successfully installed by running

[source,bash]
----
node --version
npm --version
----

==== Installation

To install the latest version of Lisk Commander as a global command,
install the NPM package like so:

[source,bash]
----
npm install --global --production lisk-commander
----

Upon successful completion, NPM will add the Lisk Commander executable
to your PATH.

Too see usage examples and configuration options, check the
link:user-guide.md[Lisk Commander User Guide]. For a full reference of
all commands and their available options, check the
link:user-guide/commands.md[Command Reference].

=== Upgrade

To update your global installation to the latest version of Lisk
Commander, simply run the following command:

[source,bash]
----
npm update --global lisk-commander
----

=== Contribute to the Codebase

Everyone is invited to contribute to the Lisk Commander project. We
welcome and appreciate all contributions.

==== Github

All necessary information can be found on our
https://github.com/LiskHQ/lisk-sdk/tree/development/commander[Lisk
Commander Github].

==== Contribution Guidelines

Please be sure to read and follow our
https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md[Contribution
Guidelines].

==== Gitter

If you have any further questions please join our
https://gitter.im/LiskHQ/lisk[Gitter].
