[[lisk-mobile-for-developers]]
Lisk Mobile for developers
--------------------------

This page provides documentation for developers about how to run Lisk
Mobile from Source.

* link:#setup[Setup]
* link:#system-requirements[System requirements]
* link:#pre-installation[Pre-Installation]
** link:#git[Git]
** link:#node-js[Node.js]
** link:#node-version-manager[Node Version Manager]
** link:#watchman[Watchman]
** link:#react-native-cli[React Native CLI]
** link:#choose-emulator[Emulator]
* link:#installation[Installation]
* link:#user-guide[User Guide]
* link:#using-environment-variables[Using environment variables]
* link:#run[Run]
* link:#build[Build]
* link:#testing[Testing]

[[setup]]
Setup
~~~~~

[[system-requirements]]
System requirements
^^^^^^^^^^^^^^^^^^^

* Ubuntu 16.04 (LTS) x86_64 or later
* MacOS 10.12 (Sierra) or later

[[pre-installation]]
Pre-Installation
^^^^^^^^^^^^^^^^

[[git]]
Git
+++

Firstly, Git is needed in order to clone the project from Github.

[[ubuntu]]
Ubuntu

[source,bash]
----
sudo apt-get install -y git
----

[[macos]]
macOS

[source,bash]
----
brew update
brew install git
----

[[node.js]]
Node.js
+++++++

[[ubuntu-1]]
Ubuntu

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
----

[[macos-1]]
macOS

[source,bash]
----
brew install node@8.14.0
----

[[node-version-manager]]
Node version manager
++++++++++++++++++++

________________________________________________________________________________________________________________________________
A node version manager is optional, but recommended in order to manager
installation of different Node.JS versions conveniently.
________________________________________________________________________________________________________________________________

* Install NVM following the
https://github.com/creationix/nvm#installation[NVM installation
instructions.]
* After successful installation, install the correct version of Node.js
like so:

[source,bash]
----
nvm install 8.3.0
----

[[watchman]]
Watchman
++++++++

[[ubuntu-2]]
Ubuntu

[source,bash]
----
git clone https://github.com/facebook/watchman.git
cd watchman/
git checkout v4.9.0 # checkout latest stable release
sudo apt-get install -y autoconf automake build-essential python-dev libssl-dev libtool
./autogen.sh
./configure
make
sudo make install
----

[[macos-2]]
macOS

[source,bash]
----
brew install watchman
----

[[react-native-cli]]
React-native-CLI
++++++++++++++++

[source,bash]
----
npm i -g react-native-cli
----

[[choose-emulator]]
Choose emulator
+++++++++++++++

You can run the project in Xcode and use iOS emulators or alternatively
use Android emulators. There are several options to set up your Android
development environment. Please read React Native docs for more info.

[[ios-simulator]]
iOS Simulator

You'll need the Xcode installed in your machine to run the app in
simulator.

Follow the https://developer.apple.com/xcode/[installation instructions
by Apple] for installation.

[[android-studio]]
Android Studio

* Download and install Android Studio, following the
https://developer.android.com/studio/[instructions on android.com].
* Check the following options during installation:
* Android SDK, consider these configurations:
** compileSdkVersion: 26
** buildToolsVersion: 27.0.3
* Android SDK Platform
* Performance (Intel ® HAXM)
* Android Virtual Device

[[installation]]
Installation
^^^^^^^^^^^^

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-mobile.git
cd lisk-mobile
npm install
npm run start
----

[[user-guide]]
User Guide
~~~~~~~~~~

[[using-environment-variables]]
Using environment variables
^^^^^^^^^^^^^^^^^^^^^^^^^^^

By using environment variables, the user can - automatically login to
the application on startup, with a pre defined account during
development - connect to a custom node

In order to do so, the file `env.json` inside the `lisk-mobile`
installation folder needs to serve the needed variables.

[source,js]
----
{
 "network": "customNode", // Lisk network's name
 "address": "https://testnet.lisk.io", // Lisk network's url
 "passphrase": "drastic spot aerobic web wave tourist library first scout fatal inherit arrange", // Passphrase of your LSK account, to be filled out automatically on login
 "secondPassphrase": "second custom passphrase" // Second passphrase of your LSK account, to be filled out automatically on send process
}
----

* `network`
* `customNode` indicates, another variable `address` is set, which will
be used when Lisk Mobile is started.
* `testnet` will try to connect to a predefined testnet node, it is not
needed to set `address`. If `address` is set, it will overwrite the
predefined node.
* `address` takes an URL to a Lisk node, Lisk Mobile shall connect to.
* `passphrase` a mnemonic passphrase can be specified here, that will be
prefilled on the login screen of Lisk Mobile.
* `secondPassphrase` lets the user predefine the second passphrase for
the account as well, if it is needed.

________________________________________________________________________________________________________________________________________________________________________________________________________
`env.json` should stay empty, when commiting changes back to Github. To
achieve this in a convenient way, the user may want to run the following
command in order to ignore changes to that file in git:

[source,bash]
----
git update-index --no-assume-unchanged env.json
----
________________________________________________________________________________________________________________________________________________________________________________________________________

[[run]]
Run
^^^

[source,bash]
----
npm start
----

[[build]]
Build
^^^^^

To build a release of Lisk Mobile, that can be installed on a device.

[[android]]
Android
+++++++

[source,bash]
----
npm run build:android
----

[[ios]]
iOS
+++

[source,bash]
----
npm run build:ios
----

[[testing]]
Testing
^^^^^^^

To test if the software works as expected, run the unit tests like so:

[source,bash]
----
npm run test
----
